port: 8080
mysql_database:
  host: localhost
  port: 3306
  user: root
  password: 
  name: clean_code

# TODO: conexion a mongodb
mongo_database:
  host: HOST_TODO
  port: PORT_TODO
  user: USER_TODO
  password: PASSWORD_TODO
  name: DB_NAME_TODO